language: node_js
sudo: false
env:
    - FORCE_COLOR=true

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
    only:
        - master
        - type != push

script:
    - npm run-script test:ci
    - npm link
    - gh is

jobs:
    include:
        - stage: test
          node_js:
              - '8'
              - '9'
              - '10'
        - stage: release
          node_js: lts/*
          script: npx semantic-release

stages:
    - test
    - name: release
      if: branch = master AND type IN (push)
