language: node_js
node_js:
    - "0.12"
    - iojs
before_install:
    - sh ci.sh
script:
    - npm run-script ci
    - npm link
    - "echo optOut: true > ~/.config/configstore/insight-gh.json"
    - gh
after_success:
    - sh ci-reports.sh
